deactivate old charter when new charter is valid
w3c/Guide pull request #163
Opened 2022-07-19 07:23 UTC by xueyuanjia

2022-07-19 08:55 UTC, deniak requested changes

2022-07-19 08:55 UTC, deniak commented on process/charter.html
> +		<li>2022-07-19 Update: For recharter, deactivate the previous charter when a new charter is valid: 1) add a note to the previous charter indicating "This charter has been replaced by <a>[a newer ve
```suggestion
		<li>2022-07-19 Update: For recharters, deactivate the previous charter when a new charter is valid:
                <ol>
                    <li>add a note to the previous charter indicating "This charter has been replaced by &lt;a&gt;[a newer version]&lt/a&gt";</li>
                    <li>if the previous charter hasn't expired when a new charter is installed, deactivate the previous charter by changing its end date via <a href="https://www.w3.org/admin/dashboard">the charter admin interface</a>.</li>
                </ol>
                </li>
```

2022-07-19 10:03 UTC, koalie approved these changes

2022-07-20 06:39 UTC, xueyuanjia commented
Thanks @deniak I accidentally marked your edits "resolved" before "commit changes", my bad 😓 so I updated my original proposed text to reflect all your edits.

2022-07-27 02:47 UTC, xueyuanjia commented
hi @plehegar, I suppose this update to our Guidebook needs your approval so I requested your review. Would you like to take a look? 👀

2022-07-29 15:49 UTC, plehegar approved these changes

2022-07-29 15:49 UTC, merged