Considerations for publishing formal objections.
w3c/Guide pull request #222
Opened 2023-12-20 19:04 UTC by plehegar

Address https://github.com/w3c/w3process/issues/735 
 following https://github.com/w3c/w3process/pull/808

2023-12-20 19:05 UTC, plehegar commented
@ylafon , @koalie , any recommendation on where to publish those formal objections ? In the past, we have some in mailing lists, blogs, github issues, etc.

2023-12-21 22:29 UTC, koalie commented
> @ylafon , @koalie , any recommendation on where to publish those formal objections ? In the past, we have some in mailing lists, blogs, github issues, etc.

Yes! after the holiday break I will [implement the plan I wrote-up today](https://lists.w3.org/Archives/Team/w3t-comm/2023Dec/0282.html) now that we've converged (PLH, Ralph, me) on **creation of a new public-review-comments mailing list** for AC reviews to-be-made-public, for FOs from Members to be made public, for FOs from the public; and how to dispose of public-new-work for mechanism to welcome public comment.

2024-01-10 18:39 UTC, plehegar commented
[location for FOs](https://github.com/w3c/Guide/pull/223)

2024-01-10 19:29 UTC, tantek submitted a review, later dismissed
I can live with this (and appreciate something here rather than nothing), however I think we should reconsider (i.e. drop) "The Formal Objection does not warrant public broadcasting if it can be easily resolved (charter duration is incorrect, etc.)" because I believe even those are worth keeping as a matter of public record for more easily citing real world examples of how we can improve our processes in the future to avoid these kinds of quality issues. Will request changes to drop just that item to see if others agree.

2024-01-11 02:23 UTC, frivoal commented
I think I agree with @tantek. It might feel a bit noisy to publish FOs that end up being retracted when the Team can predict that they will be retracted. Occasionally, FOs can even be considered misunderstandings, when the FO can be resolved without changing anything, merely by talking through it with the objector.

Nonetheless, I think we should publish them all.

As @tantek said, easily fixable mistakes are often easily avoidable mistakes, and giving those publicity can help the collective learning experience.

Moreover, if the FO is withdrawn without any (public) visible trace of it ever being raised, it's not possible (for the public) if we're in a situation of having no objections, or of having trivially resolved objections, or of having substantial objection being shut down through peer pressure, bullying, corruption… I am not saying that bullying or corruption are happening, but we should avoid designing a system where peaceful and harmonious consensus look the same to the outside as abuse.

So, I'd say:
* all FOs must be published, even those that are expected to be / have been withdrawn
* to avoid drawing unproductive media attention onto members who file FOs on easily resolved matters such as charter durations and the like, the Team should anonymize such FOs as a matter of routine
* To avoid leaving people wondering what happened, when an FO is withdrawn without having to go as far as the council, the Team should post a response to the mail announcing the FO, indicating that the FO was withdrawn, and giving a quick summary as to why.

2024-01-11 02:29 UTC, frivoal commented
Unrelatedly to the previous point, I think it would also be good to have an additional guideline like:
* If there are multiple Formal Objections to the same decision or to the same AC Review, and the Team should make them all public at the same time, to avoid attracting unwarranted unbalanced media attention to a single objector among several. For the same reason, if some FOs are already public, for instance because the objector made it public themselves, the Team should make any other FO to the same decision or to the same AC Review public without delay.

2024-01-11 07:51 UTC, koalie commented
FWIW, I can live with the whole original content of the PR AND with the first bullet removed per @tantek but people hardly bother to make *formal* objections for minor and "easily fixable" things; they're usually in addition to more serious issues that do warrant a "formal" objection.

In any case, anyone can write to the list, so we might end up with such comments being sent. This makes the guideline in the first bullet in question less relevant, and less easy to follow.

Regarding the second point @frivoal raised, I agree.

2024-01-11 15:44 UTC, plehegar commented
> So, I'd say:
> 
> * all FOs must be published, even those that are expected to be / have been withdrawn

ok. 

> * to avoid drawing unproductive media attention onto members who file FOs on easily resolved matters such as charter durations and the like, the Team should anonymize such FOs as a matter of routine

ok. I think this would alleviate the issue we encountered on DiD 1.0 formal objections where only one of the FOs was made public and attributed (by the org itself) and the 2 others weren't made public for a long time.

> * To avoid leaving people wondering what happened, when an FO is withdrawn without having to go as far as the council, the Team should post a response to the mail announcing the FO, indicating that the FO was withdrawn, and giving a quick summary as to why.

sounds like a sensitive approach.

2024-01-11 15:55 UTC, plehegar commented
> I'm ok with that as well, except that this should only happen after the end of the AC Review.

actually, I started the list with "within the 90 days investigation and mediation period", so it's already addressed.

2024-01-11 16:11 UTC, plehegar commented
ok, I think I integrated everything. One tweak: I did say that the Team must follow on ALL FOs with the conclusion. This includes when an FO is overruled by a council.

2024-01-11 16:56 UTC, npdoty commented
I have recently experienced filing a formal objection for a matter that I thought was important but that I expected to be resolved simply without involving large changes or group/AC work. I didn't make it public myself in part because I didn't want to create additional noise or confusion to people outside of the W3C Process. I do think noise and confusion are risks that should be considered about automatically publishing all formal objections. (Those risks may not be overriding, I'm not sure, just indicating that they are meaningful.)

The last point about a disposition of comments or Team update on what happened seems like the most useful time to indicate publicly that there were objections about this timing or this wording and they were resolved in this way.

2024-01-12 02:20 UTC, frivoal approved these changes

2024-01-24 15:16 UTC, TallTed requested changes
minor polish

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +    href='https://lists.w3.org/Archives/Public/public-review-comments/'>public-review-comments</a> and no later than when the
```suggestion
    href='https://lists.w3.org/Archives/Public/public-review-comments/'>public-review-comments</a>, no later than when the
```

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +      be / have been withdrawn.
```suggestion
      be — or have already been — withdrawn.
```

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +    <li>The Formal Objection ought to be made public as soon as it is
to match capitalization of the rest of the list
```suggestion
    <li>the Formal Objection ought to be made public as soon as it is
```

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +      to avoid unproductive attention onto members who file formal objections
```suggestion
      to avoid unproductive attention on members who file formal objections
```

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +      and the Team should make them all public at the same time, to avoid attracting unwarranted
```suggestion
      the Team should make them all public at the same time, to avoid attracting unwarranted
```

2024-01-24 15:16 UTC, TallTed commented on council/council.html
> +      public themselves, the Team should make any other formal objection to the same decision or
```suggestion
      some formal objections are already public — for instance, if the objector made it
      public themselves — the Team should make any other formal objection to the same decision or
```

2024-04-25 14:44 UTC, merged