Apply the new design to the guidebook
w3c/Guide pull request #267
Opened 2024-11-20 09:09 UTC by deniak

@lcarcone @vivienlacourba, I'm starting this PR to redesign the guidebook.
I've redesigned 2 pages for the example:
1. the documentreview with a HTML to markdown conversion. That method will take a while unless we can find a good tool to convert the markdown but it can be tricky as some parts of the page may still require HTML (you will see I left some tags, e.g. details/summary, dl/dt/dd)
2. the standards-track index page where I kept most of the initial HTML

Happy to schedule a call to discuss the details with you

2024-11-21 10:39 UTC, deniak commented
/cc @caribouW3

2024-12-02 22:19 UTC, TallTed commented
It would be far easier to review this if there were a pr-preview or similar. What are the chances such could be instituted?

2024-12-03 04:54 UTC, deniak commented
> It would be far easier to review this if there were a pr-preview or similar. What are the chances such could be instituted?

@TallTed it might be difficult to integrate this with pr-preview. pr-preview works for specs that use a generator such as respec and bikeshed and it's meant to preview a single file.
In that particular case, jekyll generates pages for the whole repository which could represent a lot of files.

2024-12-03 18:43 UTC, TallTed commented
> pr-preview works for specs that use a generator such as respec and bikeshed and it's meant to preview a single file

OK, pr-preview isn't a suitable tool, here. That possibility is why I said "or similar".

2024-12-04 18:50 UTC, TallTed commented on chair/role.md
> +- *Ensures* all participants have proper access to Group data *with assistance from Staff Contact.*
```suggestion
- Maintains close coordination with W3C *Staff Contact.*
- Maintains coordination with assigned liaisons from other W3C working groups.
- Participates in the Chairs mailing list ([archive](https://lists.w3.org/Archives/Member/chairs/)) and attends Chairs meetings.
  *the Team Contact should make sure the Chair is in the [Chairs group](/admin/othergroups/31972/show)* (should be managed automatically)
- Works with the Communications Team and Team Contact in preparing press release.
- Communicates with the press, when necessary and appropriate, and with prior coordination with the communication team, on behalf of the group.
- *Ensures all participants have proper access to Group data with assistance from Staff Contact.*
```

2024-12-10 12:10 UTC, deniak commented on council/council.md
> +### [I. Considerations](#considerations)
```suggestion
### I. Considerations
```

2024-12-10 12:10 UTC, deniak commented on council/council.md
> +### [II. Convincing the W3C Council](#convincing-the-council)
```suggestion
### II. Convincing the W3C Council
```

2024-12-10 12:10 UTC, deniak commented on council/council.md
> +## [Best Practices](#best-practices)
```suggestion
## Best Practices
```

2024-12-10 15:43 UTC, vivienlacourba requested changes

2024-12-18 18:06 UTC, TallTed commented
This is a HUGE change to the document. It's near impossible to coherently review, made worse by the apparent mix of markup and content changes. I cannot recommend strongly enough that this PR be re-attempted as multiple PRs, breaking it into *at least* _changes to content_ and _changes to markup_, if not into multiple PRs comprising each of these. Lacking such breakup, it is all but certain that unintended changes will go undetected.

2025-01-06 20:13 UTC, TallTed commented on process/predicting-milestones.md
>  : When developing materials for and advance notice, try to strike a balance between fast (but overly sketchy and vague) and thorough (but slow, maybe over-detailed or over-constraining).
```suggestion
: When developing materials for an advance notice, try to strike a balance between fast (but overly sketchy and vague) and thorough (but slow, maybe over-detailed or over-constraining).
```

2025-01-06 20:18 UTC, TallTed commented on process/predicting-milestones.md
>  : If feedback indicates disagreement on scope, consider proposing both a fast initial version *and* a requirements gathering and drafting item for a full-featured second version. This will help avoid
```suggestion
: If feedback indicates disagreement on scope, consider proposing both a fast initial version *and* a requirements gathering and drafting item for a full-featured second version. This can help avoid delays due to disagreements on scope.
```

2025-01-06 20:19 UTC, TallTed commented on process/predicting-milestones.md
>    Keep the proposed charter unchanged (so the AC has a stable document to review) but make a copy at a different location and incorporate comments (so commentors can see the resolution of their issue
```suggestion
  Keep the proposed charter unchanged (so the AC has a stable document to review) but make a copy at a different location and incorporate comments (so commenters can see the resolution of their issues in-place).
```

2025-01-06 20:20 UTC, TallTed commented on process/predicting-milestones.md
>  Once the decision to start the Working Group has been communicated to the AC, participants can join. This may take some time, particularly if participants need to perform a legal review of the work i
```suggestion
Once the decision to start the Working Group has been communicated to the AC, participants can join. This may take some time, particularly if participants need to perform a legal review of the work items (for example, to review their patent portfolio in light of the [W3C Royalty-Free commitment](/policies/patent-policy/#sec-Requirements)). In the case of a new group, some or all of the participants may be unfamiliar with W3C processes and tools (such as IRC, phone conferencing, issue tracking, version control). The Chair and Staff Contact take a lead role in getting a new group up to productive speed.
```

2025-01-06 20:22 UTC, TallTed commented on process/predicting-milestones.md
>  :  There is no set period until a Group starts to become productive. Experienced participants with a capable Chair and Team Contact, working on a new version of an existing specification can be produ
```suggestion
:  There is no set period after which a Group becomes productive. Experienced participants with a capable Chair and Team Contact, working on a new version of an existing specification, can be productive immediately. A new group with participants new to W3C, working in a new area which is rife with intellectual property concerns, may take several months to become productive.
```

2025-01-06 20:30 UTC, TallTed commented on process/predicting-milestones.md
>  : The minimum duration for the Wide Review comment period should be 4 weeks.
```suggestion
: The minimum duration for the Wide Review comment period is 4 weeks.
```

2025-01-06 20:41 UTC, TallTed commented on process/predicting-milestones.md
>  : 'Horizontal' groups that review many specifications (for example, WAI P&amp;F and I18n Core) may, because of their workload, need longer than the minimum period.
[WAI P&amp;F](https://www.w3.org/WAI/PF/) is defunct. This example should be replaced (and if an abbreviation or shortname is used, the long name should also be included).

```suggestion
: 'Horizontal' groups that review many specifications (for example, WAI P&amp;F, and [Internationalization Working Group (i18n-core)](https://www.w3.org/groups/wg/i18n-core/)) may, because of their workload, need longer than the minimum period.
```

2025-01-06 20:43 UTC, TallTed commented on process/predicting-milestones.md
>  Each Candidate Recommendation review comment must be documented, the changes made (if any) and rationale for the change documented, and the agreement or disagreement of the reviewer to the change als
```suggestion
Each Candidate Recommendation review comment must be documented; the changes (if any) made and their rationale documented; and the agreement or disagreement by the reviewer to the change also documented.
```

2025-01-06 20:45 UTC, TallTed commented on process/predicting-milestones.md
>    If review comments are vague, ask for clarification or for concrete specification text which would satisfy the comment.
```suggestion
  If review comments are vague, ask for clarification or for concrete specification text which would satisfy the commenter.
```

2025-01-06 20:47 UTC, TallTed commented on process/predicting-milestones.md
>  Publication of a Candidate Recommendation triggers an Exclusion period on all features which were not in the previous First Public Working Draft (or previous Candidate Recommendation, if there was on
```suggestion
Publication of a Candidate Recommendation triggers an Exclusion period on all features which were not in the preceding First Public Working Draft (or previous Candidate Recommendation, if there was one).
```

2025-01-06 20:48 UTC, TallTed commented on process/predicting-milestones.md
>  2. dropping features which were not marked as 'at risk', or adding new features as a result of implementer feedback (which leads to another Candidate Recommendation).
```suggestion
2. dropping features which were not marked as 'at risk', or adding new features as a result of implementer feedback (either of which leads to another Candidate Recommendation).
```

2025-01-06 20:51 UTC, TallTed commented on process/predicting-milestones.md
>    If in doubt, leave a feature in the spec and mark it 'at risk'. You can drop it without having another LC. Adding it back in afterwards, however, or dropping it without having identified it as 'at
I *think* Last Calls have been deprecated. Maybe `another CR` communicates what was meant?
```suggestion
  If in doubt, leave a feature in the spec and mark it 'at risk'. You can drop it without having another CR. Adding it back in afterwards, however, or dropping it without having identified it as 'at risk', triggers another Candidate Recommendation.
```

2025-01-06 20:52 UTC, TallTed commented on process/predicting-milestones.md
>  : The minimum duration for the PR review period is [four weeks](/policies/process/#rec-pr), followed by two weeks for a W3C's decision. If the review period spans the July/August or December holiday
```suggestion
: The minimum duration for the PR review period is [four weeks](/policies/process/#rec-pr), followed by two weeks for a W3C decision. If the review period spans the July/August or December holiday periods, more time is typically added.
```

2025-01-06 20:52 UTC, TallTed commented on process/predicting-milestones.md
>  : Personally contact the AC representative for each organization on the group (cc'ing the Group member) to remind them of the review.
```suggestion
: Personally contact the AC representative for each organization on the group (CCing the Group member) to remind them of the review.
```

2025-01-07 07:21 UTC, vivienlacourba commented on chair/meetings.md
> +<blockquote>
Code was updated to use the quote component.

2025-01-07 07:23 UTC, vivienlacourba commented on council/council.md
> +### Revision History
This was fixed.

2025-01-10 15:47 UTC, vivienlacourba approved these changes

2025-01-10 16:46 UTC, vivienlacourba commented
Hi @plehegar, @caribouW3, @koalie,

@lcarcone, @deniak and I worked on the Guidebook redesign, here is what was done:
- Converted content from HTML to Markdown, except for a few pages like the Manual of style (which is a Respec document) or transitions pages (which have forms relying on javascript).
- Applied the new W3C Design thanks to the [W3C Jekyll theme](https://github.com/w3c/w3c-jekyll-theme/).
- Ran the link checker and updated links on all pages.

We have deployed a test site here for you to review: https://deniak.github.io/guide/
Please review and comment on this MR.

Here is some suggested next steps which could be tackled after merging this PR:
- Review menu on the right side. I believe it should link to each individual section (folders) of the Guidebook.
- Create individual index pages for each subsections.
- Shorten content of the main index page which would then introduce each subsections. Today it has a lot of content and links. I believe it might be good to move some of this content to individual sub-sections.
- Migrate content that is still in CVS to this Guidebook, Systeam can help with that.

2025-01-13 10:52 UTC, koalie approved these changes

2025-01-13 11:06 UTC, vivienlacourba commented on .github/workflows/jekyll-gh-pages.yml
> +    branches: ["new-design"]
Branch to change from "new-design" to "main" right before merging this PR.

```suggestion
    branches: ["main"]
```

2025-01-13 14:22 UTC, plehegar commented on .github/workflows/jekyll-gh-pages.yml
> +        uses: actions/deploy-pages@v1
Consider using [@v4](https://github.com/actions/deploy-pages?tab=readme-ov-file#usage) instead.

2025-01-13 14:24 UTC, plehegar commented on .github/workflows/jekyll-gh-pages.yml
> +        uses: actions/upload-pages-artifact@v1
```suggestion
        uses: actions/upload-pages-artifact@v3
```

2025-01-13 14:24 UTC, plehegar commented on .github/workflows/jekyll-gh-pages.yml
> +        uses: actions/deploy-pages@v1
```suggestion
        uses: actions/deploy-pages@v4
```

2025-01-13 19:11 UTC, TallTed commented on README.md
>  Note: now that we have a repository for the guidebook, simply add your documentation into it rather than creating new repositories.
```suggestion
Note: now that we have a repository for the guidebook, simply add your documentation to it, rather than creating new repositories.
```

2025-01-13 19:22 UTC, TallTed reviewed
small stuff

2025-01-13 19:22 UTC, TallTed commented on chair/buddy.md
> +- The W3C Project Lead proceeds to pairing those who request to have a buddy, with those who volunteer to be a buddy.
```suggestion
- The W3C Project Lead proceeds to pair those who request a buddy with those who volunteer to be a buddy.
```

2025-01-13 19:22 UTC, TallTed commented on chair/buddy.md
> +- Try to speak to your buddy-mentee every quarter. The job of arranging meetings should be with the buddy-mentee, but it doesn't hurt to send them a quick email every so often!
```suggestion
- Arrange an initial meeting with your buddy-mentee. This can be a teleconference, or face-to-face if you live in the same area or are participating in the same meeting.
- Buddy meetings can be managed however you wish, some suggestions are given below:
  - Ask questions such as "how long have you been chairing?", "what is the size of your group?", "how many chairs are there?", "what are your group working practices?", "how do you manage and conduct meetings?", "how many documents and editors do you have?", "what are your document timelines?", "tell me about your editors / participants", "where are your participants based?".
  - Finding out as much as you can about your buddy-mentee will allow you to give the best advice!
- Try to speak to your buddy-mentee every quarter. The job of arranging meetings should generally be with the buddy-mentee, but it doesn't hurt to send them a quick email every so often!
```

2025-01-13 19:22 UTC, TallTed commented on chair/buddy.md
> +Thank-you for joining the W3C Chair Buddy system! As a buddy-mentee you should have received details of your buddy. If you have not please ask the W3C Project Lead. Here are some guidelines for being
```suggestion
Thank-you for joining the W3C Chair Buddy system! As a buddy-mentee, you should have received details of your buddy. If you have not, please ask the W3C Project Lead. Here are some guidelines for being a buddy-mentee.
```

2025-01-13 19:22 UTC, TallTed commented on chair/buddy.md
> +- It's up to you to arrange these meetings (buddy-mentors may have a few mentees, so it's best for buddy-mentees to arrange meetings).
```suggestion
- Email your buddy-mentor and introduce yourself! Give details on the group you chair, whether you have a co-chair, and some quick details on the specs you're working on and the size of your group.
- Arrange an initial meeting with your buddy-mentor. This can be a teleconference, or face-to-face if you live in the same area or are participating in the same meeting.
- Buddy meetings can be managed however you wish. Some guidelines are given below:
  - You should give your buddy-mentor as much information as possible about your current chairing situation. This will help them give you the best advice!
  - You should also prepare a list of your own questions. Here are some examples: "how do you manage consensus when one or few people are blocking?", "how do you manage meetings when participants are so distributed?", "how can I help my editors get to work?", etc.
- Try to speak to your buddy-mentor roughly every quarter. You may speak to them more infrequently or frequently depending on what works for you and your buddy-mentor. In your initial meeting, try to discuss a schedule for meetings (even if you decide to do ad-hoc meetings); then arrange the meetings by sending calendar invites (or another method of your choosing).
- _It's up to you_ to arrange these meetings. (Buddy-mentors may have a few mentees, so it's best for buddy-mentees to arrange meetings.)
```

2025-01-14 21:52 UTC, TallTed approved these changes

2025-01-15 08:02 UTC, merged